/**
 * Mock NBA Data for testing and demonstration
 * Provides sample player and game data when APIs are unavailable
 */

import { BDLPlayer, BDLSeasonAverage, BDLGame } from "./nba-api.js";

export const MOCK_PLAYERS: BDLPlayer[] = [
  {
    id: 2544,
    first_name: "LeBron",
    last_name: "James",
    position: "F",
    height: "6-9",
    weight: "250",
    jersey_number: "23",
    college: "St. Vincent-St. Mary HS",
    country: "USA",
    draft_year: 2003,
    draft_round: 1,
    draft_number: 1,
    team: { id: 14, conference: "West", division: "Pacific", city: "Los Angeles", name: "Lakers", full_name: "Los Angeles Lakers", abbreviation: "LAL" },
  },
  {
    id: 278,
    first_name: "Stephen",
    last_name: "Curry",
    position: "G",
    height: "6-2",
    weight: "185",
    jersey_number: "30",
    college: "Davidson",
    country: "USA",
    draft_year: 2009,
    draft_round: 1,
    draft_number: 7,
    team: { id: 10, conference: "West", division: "Pacific", city: "Golden State", name: "Warriors", full_name: "Golden State Warriors", abbreviation: "GSW" },
  },
  {
    id: 201939,
    first_name: "Kevin",
    last_name: "Durant",
    position: "F",
    height: "6-10",
    weight: "240",
    jersey_number: "35",
    college: "Texas",
    country: "USA",
    draft_year: 2007,
    draft_round: 1,
    draft_number: 2,
    team: { id: 19, conference: "West", division: "Pacific", city: "Phoenix", name: "Suns", full_name: "Phoenix Suns", abbreviation: "PHX" },
  },
  {
    id: 162836,
    first_name: "Giannis",
    last_name: "Antetokounmpo",
    position: "F",
    height: "6-11",
    weight: "243",
    jersey_number: "34",
    college: "High School",
    country: "Greece",
    draft_year: 2013,
    draft_round: 1,
    draft_number: 15,
    team: { id: 17, conference: "East", division: "Southeast", city: "Milwaukee", name: "Bucks", full_name: "Milwaukee Bucks", abbreviation: "MIL" },
  },
  {
    id: 162774,
    first_name: "Luka",
    last_name: "Dončić",
    position: "G",
    height: "6-7",
    weight: "230",
    jersey_number: "77",
    college: "Real Madrid",
    country: "Slovenia",
    draft_year: 2018,
    draft_round: 1,
    draft_number: 3,
    team: { id: 17, conference: "West", division: "Southwest", city: "Dallas", name: "Mavericks", full_name: "Dallas Mavericks", abbreviation: "DAL" },
  },
  {
    id: 2594,
    first_name: "Kawhi",
    last_name: "Leonard",
    position: "F",
    height: "6-7",
    weight: "225",
    jersey_number: "2",
    college: "San Diego State",
    country: "USA",
    draft_year: 2011,
    draft_round: 1,
    draft_number: 15,
    team: { id: 12, conference: "East", division: "Atlantic", city: "Philadelphia", name: "76ers", full_name: "Philadelphia 76ers", abbreviation: "PHI" },
  },
  {
    id: 203999,
    first_name: "Nikola",
    last_name: "Jokić",
    position: "C",
    height: "6-11",
    weight: "284",
    jersey_number: "15",
    college: "Mega Basket",
    country: "Serbia",
    draft_year: 2014,
    draft_round: 2,
    draft_number: 41,
    team: { id: 7, conference: "West", division: "Northwest", city: "Denver", name: "Nuggets", full_name: "Denver Nuggets", abbreviation: "DEN" },
  },
  {
    id: 2738,
    first_name: "Joel",
    last_name: "Embiid",
    position: "C",
    height: "7-0",
    weight: "280",
    jersey_number: "21",
    college: "Kansas",
    country: "Cameroon",
    draft_year: 2014,
    draft_round: 1,
    draft_number: 3,
    team: { id: 12, conference: "East", division: "Atlantic", city: "Philadelphia", name: "76ers", full_name: "Philadelphia 76ers", abbreviation: "PHI" },
  },
  {
    id: 200749,
    first_name: "Anthony",
    last_name: "Davis",
    position: "F",
    height: "6-10",
    weight: "253",
    jersey_number: "3",
    college: "Kentucky",
    country: "USA",
    draft_year: 2012,
    draft_round: 1,
    draft_number: 1,
    team: { id: 14, conference: "West", division: "Pacific", city: "Los Angeles", name: "Lakers", full_name: "Los Angeles Lakers", abbreviation: "LAL" },
  },
  {
    id: 162897,
    first_name: "Damian",
    last_name: "Lillard",
    position: "G",
    height: "6-2",
    weight: "195",
    jersey_number: "0",
    college: "Weber State",
    country: "USA",
    draft_year: 2012,
    draft_round: 1,
    draft_number: 6,
    team: { id: 25, conference: "West", division: "Northwest", city: "Milwaukee", name: "Bucks", full_name: "Milwaukee Bucks", abbreviation: "MIL" },
  },
];

export const MOCK_SEASON_AVERAGES: Map<number, BDLSeasonAverage> = new Map([
  [2544, { player_id: 2544, season: 2026, games_played: 65, min: "35.0", pts: 25.4, reb: 7.8, ast: 8.1, stl: 1.2, blk: 0.6, fg_pct: 0.52, fg3_pct: 0.38, ft_pct: 0.73, turnover: 3.5, fg3m: 2.1, fg3a: 5.5 }],
  [278, { player_id: 278, season: 2026, games_played: 72, min: "34.5", pts: 29.8, reb: 5.1, ast: 6.3, stl: 0.9, blk: 0.2, fg_pct: 0.47, fg3_pct: 0.42, ft_pct: 0.92, turnover: 3.2, fg3m: 4.5, fg3a: 10.7 }],
  [201939, { player_id: 201939, season: 2026, games_played: 62, min: "36.2", pts: 27.3, reb: 6.8, ast: 5.4, stl: 0.9, blk: 1.1, fg_pct: 0.52, fg3_pct: 0.38, ft_pct: 0.87, turnover: 3.1, fg3m: 2.6, fg3a: 6.8 }],
  [162836, { player_id: 162836, season: 2026, games_played: 68, min: "35.8", pts: 31.2, reb: 11.8, ast: 5.9, stl: 1.0, blk: 1.4, fg_pct: 0.54, fg3_pct: 0.28, ft_pct: 0.65, turnover: 3.4, fg3m: 0.8, fg3a: 2.9 }],
  [162774, { player_id: 162774, season: 2026, games_played: 70, min: "36.4", pts: 32.4, reb: 8.5, ast: 8.2, stl: 1.4, blk: 0.5, fg_pct: 0.49, fg3_pct: 0.38, ft_pct: 0.79, turnover: 4.1, fg3m: 3.1, fg3a: 8.2 }],
  [2594, { player_id: 2594, season: 2026, games_played: 58, min: "33.5", pts: 23.8, reb: 6.2, ast: 3.8, stl: 1.6, blk: 0.4, fg_pct: 0.48, fg3_pct: 0.38, ft_pct: 0.88, turnover: 2.1, fg3m: 1.8, fg3a: 4.7 }],
  [203999, { player_id: 203999, season: 2026, games_played: 73, min: "34.2", pts: 26.8, reb: 12.1, ast: 9.4, stl: 1.3, blk: 0.8, fg_pct: 0.58, fg3_pct: 0.35, ft_pct: 0.82, turnover: 3.5, fg3m: 0.7, fg3a: 2.0 }],
  [2738, { player_id: 2738, season: 2026, games_played: 66, min: "34.8", pts: 33.5, reb: 10.2, ast: 4.1, stl: 1.1, blk: 1.7, fg_pct: 0.54, fg3_pct: 0.36, ft_pct: 0.88, turnover: 3.8, fg3m: 1.2, fg3a: 3.3 }],
  [200749, { player_id: 200749, season: 2026, games_played: 67, min: "35.1", pts: 24.6, reb: 12.1, ast: 3.5, stl: 1.3, blk: 2.3, fg_pct: 0.56, fg3_pct: 0.28, ft_pct: 0.78, turnover: 2.4, fg3m: 0.9, fg3a: 3.2 }],
  [162897, { player_id: 162897, season: 2026, games_played: 69, min: "36.0", pts: 28.3, reb: 4.2, ast: 7.2, stl: 1.0, blk: 0.3, fg_pct: 0.45, fg3_pct: 0.41, ft_pct: 0.91, turnover: 2.9, fg3m: 3.8, fg3a: 9.3 }],
]);

export const MOCK_GAMES: BDLGame[] = [
  {
    id: 1,
    date: new Date().toISOString(),
    home_team: { id: 14, name: "Lakers", full_name: "Los Angeles Lakers", abbreviation: "LAL" },
    visitor_team: { id: 10, name: "Warriors", full_name: "Golden State Warriors", abbreviation: "GSW" },
    home_team_score: 0,
    visitor_team_score: 0,
    season: 2026,
    status: "PRE",
    period: 0,
    time: "",
  },
  {
    id: 2,
    date: new Date().toISOString(),
    home_team: { id: 12, name: "76ers", full_name: "Philadelphia 76ers", abbreviation: "PHI" },
    visitor_team: { id: 17, name: "Bucks", full_name: "Milwaukee Bucks", abbreviation: "MIL" },
    home_team_score: 0,
    visitor_team_score: 0,
    season: 2026,
    status: "PRE",
    period: 0,
    time: "",
  },
  {
    id: 3,
    date: new Date().toISOString(),
    home_team: { id: 7, name: "Nuggets", full_name: "Denver Nuggets", abbreviation: "DEN" },
    visitor_team: { id: 19, name: "Suns", full_name: "Phoenix Suns", abbreviation: "PHX" },
    home_team_score: 0,
    visitor_team_score: 0,
    season: 2026,
    status: "PRE",
    period: 0,
    time: "",
  },
];

export function getMockPlayers(): BDLPlayer[] {
  return MOCK_PLAYERS;
}

export function getMockSeasonAverages(): Map<number, BDLSeasonAverage> {
  return MOCK_SEASON_AVERAGES;
}

export function getMockGames(): BDLGame[] {
  return MOCK_GAMES;
}
